apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  name: admin
  namespace: my-eventstreams
  labels:
    eventstreams.ibm.com/cluster: minimal-prod
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - operation: Read
        resource:
          type: topic
          name: '*'
          patternType: literal
      - operation: Write
        resource:
          type: topic
          name: '*'
          patternType: literal
      - operation: Create
        resource:
          type: topic
          name: '*'
          patternType: literal
      - operation: Delete
        resource:
          type: topic
          name: '*'
          patternType: literal
      - operation: Read
        resource:
          type: group
          name: '*'
          patternType: literal
      - operation: Alter
        resource:
          type: cluster
          name: kafka-cluster
          patternType: literal

