#
#Thu Jun 18 01:48:49 GMT 2026
acks=1
auto.offset.reset=earliest
bootstrap.servers=kafka.18-220-31-188.sslip.io\:443
client.id=starter-app-starter-app
enable.auto.commit=false
group.id=starter-app-starter-consumer
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
key.serializer=org.apache.kafka.common.serialization.StringSerializer
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username\="starter-app" password\="wPo8qjH1DwUCSdE8uQw57jweu7AcSUEE";
sasl.mechanism=SCRAM-SHA-512
security.protocol=SASL_SSL
ssl.protocol=TLSv1.2
ssl.truststore.location=truststore.p12
ssl.truststore.password=PPBrr8q5rDiW
ssl.truststore.type=PKCS12
topic=starter_topic
value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.serializer=org.apache.kafka.common.serialization.StringSerializer
